[package]
name = "rerescope"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
fuzzy-matcher = "0.3"
ignore = "0.4"
tokio = { version = "1", features = ["full"] }
